version: '2'

services:
  api:
    image: stevedevops/api-dev
    environment:
      NODE_ENV: development
    ports:
      - 3002:3000
    volumes:
      - .:/usr/src/api
    command: nodemon .
  mysqldb:
    image: stevedevops/mysql-dev
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT}'
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PWD}'
    ports:
      - 3386:3386
    volumes:
      - ../dev-db:/var/lib/mysql
